### ISSUE TITLE
[BUG] Steam Workshop not downloading

### ISSUE THREAD

**Issue by dprince2** [Foxlider/Fox-s-Arma-Server-Tool-Extended-Rewrite#91]
**Describe the bug:** When Trying to download mods for server, i press "update all" it goes into the console and looks as if everything is being downloaded, create's all folders in the directory, and shows my network usage is up in the task manager. but nothing is actually being downloaded, 

**To Reproduce:** Press update all and watch the magic happen, eventually it will timeout saying the download can not be completed.

**Expected behaviour:** Download mods in respected folders, 

**Actual behaviour:** Creates folders, but no mods are actually downloaded

**Screenshots:** Attached are screenshops of during download, showing network usage is up, but files are empty. after download has timed out, and list of incomplete.
![afterdownload](https://user-images.githubusercontent.com/34147852/80319717-f240a100-87df-11ea-84e2-8b7c01025b54.png)
![network](https://user-images.githubusercontent.com/34147852/80319720-f40a6480-87df-11ea-9069-4d4a54da9723.png)
![notcomplete](https://user-images.githubusercontent.com/34147852/80319721-f4a2fb00-87df-11ea-96d5-8afc2476d909.png)

**Comment by Foxlider** [comment]
FASTER uses SteamCMD to interact with steam. All the mods are getting downloaded one by one in the background. Once they are downloaded, they are added in steamcmd's folders just like standard Steam (steamapps\workshop\...) and a link is made between steamcmd's folder and the game folder (just like the `!@Workshop` folder )
Update all is not always working because steamcmd can't process too many commands at once. I recommend checking the mods manually or retrying with the check for updates button
